feat: exit non-zero when trying to recycle itself

diff --git a/recycle b/recycle
--- a/recycle
+++ b/recycle
@@ -17,6 +17,11 @@ validateFile() {
 		echo "$0: '$1' is a directory, but expect a file"
 		exit 3
 	fi
+
+	if [ "$(readlink -f "$1")" == "$(readlink -f "$0")" ]; then
+		echo "$0: cannot recycle itself"
+		exit 4
+	fi
 }
 
 validateArgs "$@"
