feat: write restore info when recycling a file

diff --git a/recycle b/recycle
--- a/recycle
+++ b/recycle
@@ -1,6 +1,13 @@
 #!/bin/bash
 
+restoreFile="$HOME/.restore.info"
 recycleBin="$HOME/recyclebin"
+
+createRestoreFileIfNotExist() {
+	if [ ! -e "$restoreFile" ]; then
+		touch "$restoreFile"
+	fi
+}
 
 validateArgs() {
 	if [ "$#" -le 0 ]; then
@@ -33,11 +40,30 @@ getRecycleFileName() {
 	unset inodeNumber
 }
 
+# 1st arg: recycle file name
+# 2nd arg: absolute path
+writeRecord() {
+	record="$1:$2"
+
+	if grep -Fqe "$record" "$restoreFile"; then
+		echo "$0: record '$record' already exists in '$restoreFile', you can't recycle same filename with same inode number"
+		exit 5
+	else
+		echo "$record" >>"$restoreFile"
+	fi
+}
+
 recycleFile() {
 	validateFile "$1"
-	mv "$1" "$recycleBin/$(getRecycleFileName "$1")"
+
+	absPath="$(realpath "$1")"
+	recycleFileName="$(getRecycleFileName "$1")"
+
+	mv "$1" "$recycleBin/$recycleFileName"
+	writeRecord "$recycleFileName:$absPath"
 }
 
 validateArgs "$@"
+createRestoreFileIfNotExist
 mkdir -p "$recycleBin"
 recycleFile "$1"
diff --git a/testRecycle b/testRecycle
--- a/testRecycle
+++ b/testRecycle
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+restoreFile="$HOME/.restore.info"
+restoreInfoSep=':'
 recycleBin="$HOME/recyclebin"
 tmpDir='tmpDir'
 tmpFile='tmpFile'
@@ -33,6 +35,17 @@ verifyFileExist() {
 	fi
 }
 
+# 1st arg: file name
+# 2nd arg: absolute path
+checkRestoreInfo() {
+	record="$1$restoreInfoSep$2"
+	if ! grep -Fqe "$record" "$restoreFile"; then
+		echo -en "\033[1;31mTest failed\033[0m: "
+		echo "Cannot find record '$record' in '$restoreFile'"
+		exit 3
+	fi
+}
+
 printTestMsgHeader() {
 	printf "\033[1;34mTest %s:\033[0m %s\n" "$1" "$2"
 }
@@ -41,10 +54,19 @@ clearRecycleBin() {
 	rm "$recycleBin"/*
 }
 
+clearRestoreInfo() {
+	cat /dev/null >"$restoreFile"
+}
+
+clearAll() {
+	clearRecycleBin
+	clearRestoreInfo
+}
+
 # Test cases:
 
 rm -r "$recycleBin"
-clearRecycleBin
+clearAll
 
 testExe 'no argument' 'bash ./recycle' \
 	'./recycle: no filename is provided'
@@ -63,7 +85,7 @@ touch "$tmpFile"
 inodeNumber="$(ls -i "$tmpFile" | cut -d' ' -f1)"
 testExe 'recycle single file does put into recyle bin' "bash ./recycle \"$tmpFile\""
 verifyFileExist "$recycleBin/${tmpFile}_$inodeNumber"
-clearRecycleBin
+clearAll
 
 mkdir -p "$tmpDir"
 targetFile="$tmpDir/$tmpFile"
@@ -72,4 +94,11 @@ inodeNumber="$(ls -i "$targetFile" | cut -d' ' -f1)"
 testExe 'recycle single file in a directory does put into recyle bin' "bash ./recycle \"$targetFile\""
 verifyFileExist "$recycleBin/${tmpFile}_$inodeNumber"
 rmdir "$tmpDir"
-clearRecycleBin
+clearAll
+
+touch "$tmpFile"
+absPath="$(realpath "$tmpFile")"
+inodeNumber="$(ls -i "$tmpFile" | cut -d' ' -f1)"
+testExe 'recycling file updates .restore.info' "bash ./recycle \"$tmpFile\"" ''
+checkRestoreInfo "${tmpFile}_$inodeNumber" "$absPath"
+clearAll
