test: add a main test script

diff --git a/testUtils b/testUtils
--- a/testUtils
+++ b/testUtils
@@ -1,11 +1,5 @@
 #!/bin/bash
 
-export restoreFile="$HOME/.restore.info"
-export restoreInfoSep=':'
-export recycleBin="$HOME/recyclebin"
-export tmpDir='tmpDir'
-export tmpFile='tmpFile'
-
 printTestMsgHeader() {
 	printf "\033[1;34mTest %s:\033[0m %s\n" "$1" "$2"
 }
@@ -67,3 +61,13 @@ checkRestoreInfo() {
 	fi
 }
 
+# 1st arg: file name
+# 2nd arg: absolute path
+checkRestoreInfoNotExist() {
+	record="$1$restoreInfoSep$2"
+	if grep -Fqe "$record" "$restoreFile"; then
+		echo -en "\033[1;31mTest failed\033[0m: "
+		echo "Record '$record' should not be in '$restoreFile'"
+		exit 4
+	fi
+}
